### PR TITLE
Searching functionality

### PR DESCRIPTION
**Pull request by coolfortune**
Added searching functionality, which searches the database based on class code name

### CODE REVIEW

**Comment by aguilarjavier** [comment]
Search is sweet! Only thing I can see wrong (maybe a work in prog) is that when you first log in theres an error that shows on the homescreen. toLowerCase() was called on null.

**Comment by runocan** [comment]
I also had the same error. I fixed it by just adding an or and returning true if _searchText == null. Looks very nice otherwise. Nice job! What do we do about the security check errors?

**Comment by coolfortune** [comment]
> I also had the same error. I fixed it by just adding an or and returning true if _searchText == null

push your new change?

**Comment by runocan** [comment]
pushed!

**Review by runocan — APPROVED** [review]

**Review by aguilarjavier — APPROVED** [review]

**Pull request merged**
